modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL = "https://github.com/Cryptic-Mushroom/The-Midnight/issues"
license = "Custom License, see GitHub"

[[mods]]
modId="midnight"
version="${version}"
displayName="The Midnight"
updateJSONURL="https://raw.githubusercontent.com/Cryptic-Mushroom/The-Midnight/rewrite/versioninfo/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/the-midnight"
logoFile="logo.png"
authors="Cryptic Mushroom's The Midnight Development Team"
description= '''
The Midnight has been rewritten from the ground up and is currently in an unstable alpha. Expect more content soon!

This mod is a huge collaborative effort with tons of different ideas, coding, and textures pitched in by varying individuals who came together to build something great. We wouldn't be where we are today without the help of those here today and those who worked on this mod in the past.

The Midnight Development Team Active Developers
Cipher Zer√∏ X - Project Lead, Mastermind, Modeler
Shadew - Lead Programmer
Jonathing - Lead QA, Community Manager, Programmer, Musician

Active Collaborators
Lachney - Lead Sound Designer, Lead Musician

Former and Inactive Developers
bagu_chan - Programmer
gegy1000 - Programmer
Martacus - Programmer
arthurbambous - Programmer
Corail31 - Programmer
Endergized - Texturer
Five (Paradiscal) - Texturer
MCVinnyq - Texturer, Modeler

The Midnight is still in active development and we'd love to hear your feedback! Click the link near the top of this page to view information on our Discord server, active developers, and plans for the future of this mod.
'''

[[dependencies.midnight]]
    modId="forge"
    mandatory=true
    versionRange="[34.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.midnight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
