site_name: The Midnight Wiki
site_dir: '/home/docs/checkouts/readthedocs.org/user_builds/the-midnight/builds/latest/'
docs_dir: '/home/docs/checkouts/readthedocs.org/user_builds/the-midnight/checkouts/latest/'
